// <auto-generated />
using System;
using AD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AD.Migrations
{
    [DbContext(typeof(ADContext))]
    [Migration("20240513095535_mor8")]
    partial class mor8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AD.Models.ADDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DomainControllerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LdapFormat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DomainController");
                });

            modelBuilder.Entity("AD.Models.ADEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool?>("IsCreatedAD")
                        .HasColumnType("bit");

                    b.Property<string>("OU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserAccountNamesid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UserAccountNamesid")
                        .IsUnique()
                        .HasFilter("[UserAccountNamesid] IS NOT NULL");

                    b.ToTable("ADEntity");
                });

            modelBuilder.Entity("AD.Models.ADOU", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("OUName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OUPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ADOU");
                });

            modelBuilder.Entity("AD.Models.AllowedUsers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isAllowed")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("AllowedUsers");
                });

            modelBuilder.Entity("AD.Models.GoogleDomain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("GoogleDomain");
                });

            modelBuilder.Entity("AD.Models.GoogleOU", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OUName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OUPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("GoogleOU");
                });

            modelBuilder.Entity("AD.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("AD.Models.UserAccountNames", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserName")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("workerType")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("UserAccountNames");
                });

            modelBuilder.Entity("AD.Models.ADEntity", b =>
                {
                    b.HasOne("AD.Models.UserAccountNames", "UserAccountNames")
                        .WithOne("ADEntity")
                        .HasForeignKey("AD.Models.ADEntity", "UserAccountNamesid");

                    b.Navigation("UserAccountNames");
                });

            modelBuilder.Entity("AD.Models.UserAccountNames", b =>
                {
                    b.Navigation("ADEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
